In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
df=pd.DataFrame({'review':['This is a good movie','This is a bad movie','This is an excellent movie','This is a terrible movie'],'rating':[1,1,0,0]})
cv=CountVectorizer()
x=cv.fit_transform(df['review'])
print(cv.vocabulary_)
print(x.toarray())


{'this': 7, 'is': 4, 'good': 3, 'movie': 5, 'bad': 1, 'an': 0, 'excellent': 2, 'terrible': 6}
[[0 0 0 1 1 1 0 1]
 [0 1 0 0 1 1 0 1]
 [1 0 1 0 1 1 0 1]
 [0 0 0 0 1 1 1 1]]


In [ ]:
cv=CountVectorizer(ngram_range=(2,2))
x=cv.fit_transform(df['review'])
print(cv.vocabulary_)
print(x.toarray())

{'this is': 9, 'is good': 6, 'good movie': 3, 'is bad': 5, 'bad movie': 1, 'is an': 4, 'an excellent': 0, 'excellent movie': 2, 'is terrible': 7, 'terrible movie': 8}
[[0 0 0 1 0 0 1 0 0 1]
 [0 1 0 0 0 1 0 0 0 1]
 [1 0 1 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 1 1]]


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(ngram_range=(2,2))
x=tfidf.fit_transform(df['review'])
print(tfidf.vocabulary_)
print(x.toarray())

{'this is': 9, 'is good': 6, 'good movie': 3, 'is bad': 5, 'bad movie': 1, 'is an': 4, 'an excellent': 0, 'excellent movie': 2, 'is terrible': 7, 'terrible movie': 8}
[[0.         0.         0.         0.66338461 0.         0.
  0.66338461 0.         0.         0.34618161]
 [0.         0.66338461 0.         0.         0.         0.66338461
  0.         0.         0.         0.34618161]
 [0.55280532 0.         0.55280532 0.         0.55280532 0.
  0.         0.         0.         0.28847675]
 [0.         0.         0.         0.         0.         0.
  0.         0.66338461 0.66338461 0.34618161]]


In [2]:
import opendatasets as od
import pandas as pd
od.download("https://www.kaggle.com/datasets/saurabhbadole/game-of-thrones-book-dataset?select=1+-+A+Game+of+Thrones.txt")

Skipping, found downloaded files in ".\game-of-thrones-book-dataset" (use force=True to force download)


In [3]:
df=pd.read_csv("game-of-thrones-book-dataset/1 - A Game of Thrones.txt", sep="\t", header=None, names=["review", "rating"] )
print(df.head())

                                              review  rating
0                                 A Game Of Thrones      NaN
1                Book One of A Song of Ice and Fire      NaN
2                            By George R. R. Martin      NaN
3                                          PROLOGUE      NaN
4  We should start back, Gared urged as the woods...     NaN


In [4]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91955\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\91955\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [11]:
import pandas as pd
import numpy as np
import gensim
import os
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91955\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [1]:
import os
import nltk
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess
from gensim.models import Word2Vec

# Download tokenizer resources (run once)
nltk.download('punkt')
nltk.download('punkt_tab')

# Dataset folder path
data_path = r'game-of-thrones-book-dataset'

story = []

# Read all txt files
for filename in os.listdir(data_path):
    if filename.endswith('.txt'):
        file_path = os.path.join(data_path, filename)

        with open(file_path, 'r', encoding='latin-1') as f:
            corpus = f.read()

            # Split into sentences
            sentences = sent_tokenize(corpus)

            # Convert each sentence into cleaned word tokens
            for sent in sentences:
                tokens = simple_preprocess(sent)
                story.append(tokens)

print(story[:5])


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91955\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\91955\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


[['game', 'of', 'thrones', 'book', 'one', 'of', 'song', 'of', 'ice', 'and', 'fire', 'by', 'george', 'martin', 'prologue', 'we', 'should', 'start', 'back', 'gared', 'urged', 'as', 'the', 'woods', 'began', 'to', 'grow', 'dark', 'around', 'them'], ['the', 'wildlings', 'are', 'dead'], ['do', 'the', 'dead', 'frighten', 'you'], ['ser', 'waymar', 'royce', 'asked', 'with', 'just', 'the', 'hint', 'of', 'smile'], ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait']]


In [ ]:
model = Word2Vec(
    sentences=story,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

# Example: similar words
print(model.wv.most_similar('viserys')) 

[('dany', 0.5847765803337097), ('someone', 0.5687721371650696), ('sleep', 0.5687203407287598), ('cry', 0.5665279030799866), ('brienne', 0.5582542419433594), ('she', 0.5569333434104919), ('arya', 0.556443989276886), ('sam', 0.5512998700141907), ('yoren', 0.5470337867736816), ('pie', 0.5198965668678284)]


In [25]:
print(model.wv['deep'].shape)
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
x=pca.fit_transform(model.wv.get_normed_vectors())
print(x)
index = model.wv.key_to_index['deep']
print(x[index])
print(x.shape)

(100,)
[[ 0.1098896  -0.53634363 -0.0411677 ]
 [ 0.10024714 -0.27019715  0.04976822]
 [-0.3104292  -0.6120408   0.10930394]
 ...
 [-0.18066452  0.13994178 -0.04905134]
 [ 0.18994409  0.11025456  0.03382884]
 [-0.02880972 -0.34039718 -0.06049605]]
[ 0.6063566  -0.25177974  0.04615812]
(17453, 3)
